[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"

auto_detect_solc = true
optimizer = true
optimizer_runs = 200

ffi = true
gas_limit = 30000000

[profile.default.fuzz]
runs = 1024

fs_permissions = [
  { access = "read", path = "/" },
  { access = "read-write", path = "./out" },
]
